CREATE TABLE HOTEL (
HotelID	    VARCHAR(15)	 NOT NULL,
HotelName		VARCHAR(20)	 NOT NULL,
HotelAdress	VARCHAR(20),
PRIMARY KEY (HotelID),
UNIQUE (HotelName) );

CREATE TABLE CUSTOMER (
CSSN	          VARCHAR(15)	 NOT NULL,
CustFirstName		VARCHAR(20)	 NOT NULL,
CustLastName	  VARCHAR(20)	 NOT NULL,
CustMail		    VARCHAR(30),
PRIMARY KEY (CSSN) );

CREATE TABLE ROOMS (
RoomID	      VARCHAR(15)	 NOT NULL,
RoomNumber		INTEGER	     NOT NULL,
HotlID		    VARCHAR(15),
PRIMARY KEY (RoomID, RoomNumber),
FOREIGN KEY (HotlID) REFERENCES HOTEL(HotelID)  );

CREATE TABLE BILL (
BillID	    VARCHAR(15)	 NOT NULL,
BillTime		DATE	       NOT NULL,
BillMethod	VARCHAR(20),
PRIMARY KEY (BillID) );

CREATE TABLE PAYMENT (
PayID	    VARCHAR(15)	 NOT NULL,
PayTime		DATE	       NOT NULL,
PayMethod	VARCHAR(20),
CSSN	    VARCHAR(20),
PRIMARY KEY (PayID),
FOREIGN KEY (CSSN) REFERENCES CUSTOMER(CSSN) );

CREATE TABLE DEPENDENT (
DName		  VARCHAR(20)	 NOT NULL,
DGender		VARCHAR(15),
DRelation	VARCHAR(30),
CSSN		  VARCHAR(15),
PRIMARY KEY (DName),
FOREIGN KEY (CSSN) REFERENCES CUSTOMER(CSSN) );

CREATE TABLE CUSTPHONE (
CustPhone		VARCHAR(15)	 NOT NULL,
CSSN		    VARCHAR(15),
PRIMARY KEY (CustPhone),
FOREIGN KEY (CSSN) REFERENCES CUSTOMER(CSSN) );

ALTER TABLE HOTEL
MODIFY HotelID VARCHAR2(25)  NOT NULL;

ALTER TABLE DEPENDENT 
ADD Mail  VARCHAR2(20) ;

INSERT INTO CUSTOMER
VALUES (15423 , 'Mohamed', 'Ahmed');

UPDATE ROOMS 
SET RoomNumber = 21
WHERE RoomID = 421;

DELETE FROM PAYMENT 
WHERE PayMethod = 'Card';

SELECT * FROM CUSTOMER 
WHERE CSSN = 24532;

SELECT PayTime 
FROM PAYMENT 
WHERE PayMethod = 'Visa' OR  PayMethod = 'Cash';

SELECT * FROM CUSTOMER 
WHERE  CustFirstName  LIKE  '%ed';

SELECT * FROM ROOMS
WHERE RoomNumber  BETWEEN 410 AND 420; 

COMMIT;

